package validation

const (
	ERR_INVALID_CHARS = "PARAM CONTENTS INVALID"
	ERR_RANGE_EXCEED = "PARAM VALUE IS OUT OF RANGE BOUNDS"

	ERR_NOT_OBJECT = "PARAM IS NOT AN OBJECT"
	ERR_NOT_ARRAY = "PARAM IS NOT AN ARRAY"
	ERR_NOT_STRING = "PARAM IS NOT A STRING"
	ERR_NOT_INT = "PARAM IS NOT AN INT"
	ERR_NOT_INT64 = "PARAM IS NOT AN INT64"
	ERR_NOT_FLOAT64 = "PARAM IS NOT A FLOAT64"
	ERR_NOT_BOOL = "PARAM IS NOT A BOOLEAN"

	ERR_PARSE_INT64 = "PARAM FAILED TO PARSE AS INT64"
	ERR_PARSE_FLOAT64 = "PARAM FAILED TO PARSE AS FLOAT64"
	ERR_PARSE_TIME = "PARAM FAILED TO PARSE AS TIME"
	ERR_PARSE_URL = "PARAM FAILED TO PARSE AS URL"
)
